### PR TITLE
NPM Packaging on release

### PR DESCRIPTION
**Pull request by MelissaAutumn**
Here's the changes to make it publish to npm on the creation of a new release. We'll need to adjust the version after this is merged in. But the usual tag a version `tags/v0.1.4` for example, and create a release off will trigger a push to npm.

### CODE REVIEW

**Comment by MelissaAutumn** [comment]
cc @jobisoft

**Comment by jobisoft** [comment]
Thanks @MelissaAutumn !

I made a new release and got this report:
https://github.com/thunderbird/webext-compat-data/actions/runs/10564487299/job/29266954951

Any idea?

Is the workflow actually running the generator script? I don't think this is needed, since the generated file is part of the release, so the npm package could use it directly: https://github.com/thunderbird/webext-compat-data/blob/main/thunderbird_compat_data.js

**Comment by MelissaAutumn** [comment]
Heya! That error basically means you have to change the version number in package.json!

The workflow shouldn't be running the generator script, but it provides a way for the enduser to run it. But I can double check when Im back nexy week.

**Comment by jobisoft** [comment]
Thanks! That did the trick. I will file a follow-up issue for something which I have observed and do not want to forget. No urgency.

**Pull request merged**
